name: verbal_expressions
description: A package that helps to construct difficult regular expressions.
version: 0.0.1
author: Ne4istb <anechytailov@gmail.com>
homepage: https://github.com/VerbalExpressions/DartVerbalExpressions

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
