name: verbal_expressions
description: A package that helps to construct difficult regular expressions.
version: 0.4.0
author: Ne4istb <anechytailov@gmail.com>
homepage: https://github.com/VerbalExpressions/DartVerbalExpressions

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: '^1.3.0'
